all: Main.class SquareFree.class ResultParser.class

Main.class: Main.java
	javac Main.java

SquareFree.class: SquareFree.java
	javac SquareFree.java

ResultParser.class: ResultParser.java
	javac ResultParser.java

run:
	java Main
